### ISSUE TITLE
Testing needs for GPT: Launch an Ansible Job thru AAP

### ISSUE THREAD

**Issue by jasperchui** [janus-idp/software-templates#153]

**Comment by rnapoles-rh** [comment]
@josephca please close if done or move to milestone 4.

**Comment by kadel** [comment]
Tested that [template](https://github.com/janus-idp/software-templates/blob/main/templates/github/launch-ansible-job/template.yaml) successfully created PR with content, but I was not able to test integration with Ansible

**Comment by kadel** [comment]
Register component step is failing with 
```
[1](http://localhost:3000/create/tasks/0eaed490-fa46-406e-a8db-8234eb2dfe0e#line-1)2023-09-13T15:25:42.000Z Beginning step Registering the Catalog Info Component[2](http://localhost:3000/create/tasks/0eaed490-fa46-406e-a8db-8234eb2dfe0e#line-2)2023-09-13T15:25:42.000Z InputError: Invalid input passed to action catalog:register, instance is not exactly one from [subschema 0],[subschema 1][3](http://localhost:3000/create/tasks/0eaed490-fa46-406e-a8db-8234eb2dfe0e#line-3)    at NunjucksWorkflowRunner.executeStep (/Users/tkral/Code/janus-showcase/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-4b7489dd.cjs.js:5956:17)[4](http://localhost:3000/create/tasks/0eaed490-fa46-406e-a8db-8234eb2dfe0e#line-4)    at async NunjucksWorkflowRunner.execute (/Users/tkral/Code/janus-showcase/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-4b7489dd.cjs.js:6070:9)[5](http://localhost:3000/create/tasks/0eaed490-fa46-406e-a8db-8234eb2dfe0e#line-5)    at async TaskWorker.runOneTask (/Users/tkral/Code/janus-showcase/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-4b7489dd.cjs.js:6292:26)[6](http://localhost:3000/create/tasks/0eaed490-fa46-406e-a8db-8234eb2dfe0e#line-6)    at async run (/Users/tkral/Code/janus-showcase/node_modules/p-queue/dist/index.js:163:29)
```

in Ansible Job definition  there is a weird value for Extra Vars : `[object Object]`

**Comment by kadel** [comment]
testing done, opened https://github.com/janus-idp/software-templates/issues/161 to track bug that caused the failure
